/* 한문 야@르 · 오프라인 성어 학습. 학습지의 성어 정리만 수록합니다. */
'use strict';
const CARDS = [
 ['竹馬故友','죽마고우','대나무 죽|말 마|옛 고|벗 우','대나무 말을 타고 함께 놀던 옛 친구','어려서 함께 놀던 친구','1234'],
 ['莫逆之友','막역지우','없을 막|거스릴 역|어조사 지|벗 우','거스름이 없는 친구','허물없이 아주 친한 친구','2134'],
 ['朋友有信','붕우유신','벗 붕|벗 우|있을 유|믿을 신','벗과 벗 사이에는 믿음이 있어야 함','친구 사이의 도리는 신의와 믿음에 있음','1243'],
 ['知己之友','지기지우','알 지|몸/자기 기|어조사 지|벗 우','나를 알아주는 친구','내 마음을 헤아려 주는 친구','2134'],
 ['知音','지음','알 지|소리 음','소리를 알다','내 마음을 헤아려 주는 친구','21'],
 ['伯牙絶絃','백아절현','맏 백|어금니 아|끊을 절|악기줄 현','백아가 거문고줄을 끊다','내 마음을 헤아려 주는 친구','1243'],
 ['破竹之勢','파죽지세','깨뜨릴 파|대나무 죽|어조사 지|형세 세','대나무를 쪼개는 기세','막을 수 없을 정도로 맹렬하게 기세를 뻗치는 모양','2134'],
 ['文房四友','문방사우','글월 문|방 방|넉 사|벗 우','글방(서재)의 네 벗','서재에 꼭 필요한 네 가지 도구 (종이·붓·먹·벼루)','1234'],
 ['管鮑之交','관포지교','대롱/관중 관|절인 고기/포숙 포|어조사 지|사귈 교','관중과 포숙의 사귐','우정이 아주 돈독한 친구 관계','1234'],
 ['教學相長','교학상장','가르칠 교|배울 학|서로 상|자랄 장','가르치고 배우며 서로 성장함','가르치고 배우는 과정에서 스승과 제자가 함께 성장함','1234'],
 ['手不釋卷','수불석권','손 수|아니 불|풀/놓을 석|책 권','손에서 책을 놓지 않음','책을 가까이 하며 늘 글을 읽음','1432'],
 ['晝耕夜讀','주경야독','낮 주|밭갈 경|밤 야|읽을 독','낮에는 농사짓고, 밤에는 글을 읽음','어려운 여건 속에서도 꿋꿋이 공부함','1234'],
 ['螢雪之功','형설지공','반딧불이 형|눈 설|어조사 지|공로 공','반딧불이와 눈의 공로','고생을 하면서 부지런하고 꾸준하게 공부하는 자세','1234'],
 ['結草報恩','결초보은','묶을 결|풀 초|갚을 보|은혜 은','풀을 묶어서 은혜를 갚음','죽어서도 은혜를 잊지 않고 갚음','2143'],
 ['四面楚歌','사면초가','넉 사|얼굴/쪽 면|초나라 초|노래 가','사면에서 들려오는 초나라 노래','아무에게도 도움이나 지지를 받을 수 없는 고립된 상태','1234'],
 ['漁父之利','어부지리','고기 잡을 어|아비 부|어조사 지|이로울 리','어부의 이익','둘이 다투는 사이에 제3자가 힘들이지 않고 이익을 얻음','1234'],
 ['朝三暮四','조삼모사','아침 조|석 삼|저녁 모|넉 사','아침에 3개, 저녁에 4개','① 간사한 꾀로 남을 속임 / ② 눈앞의 차이에만 현혹되는 어리석음','1234'],
 ['咸興差使','함흥차사','다 함|일어날 흥|사신보낼 차|사신 사','함흥으로 간 차사(사신)','심부름을 가서 소식이 없거나 돌아오지 않는 사람','1234'],
 ['鷄卵有骨','계란유골','닭 계|알 란|있을 유|뼈 골','달걀에 뼈가 있음','운 나쁜 사람은 좋은 기회를 만나도 일이 풀리지 않음','1243'],
 ['指鹿爲馬','지록위마','가리킬 지|사슴 록|할 위|말 마','사슴을 가리켜 말이라고 함','윗사람을 농락하여 권세를 휘두름 / 윗사람을 속여 올바른 판단을 하지 못하게 함','2143'],
 ['狐假虎威','호가호위','여우 호|빌릴 가|범 호|위엄 위','여우가 호랑이의 위엄을 빌림','남의 권세를 빌려 위세를 부림','1423'],
 ['寸鐵殺人','촌철살인','마디 촌|쇠 철|죽일 살|사람 인','한 치의 쇠붙이로도 사람을 죽일 수 있음','간단한 말로 핵심을 찔러 상대를 감동시키거나 충격을 줌','1243'],
 ['易地思之','역지사지','바꿀 역|땅/처지 지|생각할 사|것 지 (대명사)','처지를 바꾸어 그것을 생각함','상대방의 처지나 입장에서 생각해 봄','2143'],
 ['吾鼻三尺','오비삼척','나 오|코 비|석 삼|자 척','내 코가 석자다.','자기 사정이 급하여 남을 돌볼 겨를이 없음','1234'],
 ['坐井觀天','좌정관천','앉다 좌|우물 정|보다 관|하늘 천','우물 속에 앉아서 하늘을 본다.','사람의 견문(見聞)이 매우 좁음','2143'],
 ['烏飛梨落','오비이락','까마귀 오|날다 비|배나무 리|떨어지다 락','까마귀가 날자 배가 떨어진다.','아무 관계 없는 일이 우연히 동시에 일어나 남의 의심을 받게 됨','1234'],
 ['牛耳讀經','우이독경','소 우|귀 이|읽다 독|글 경','소귀에 경서(글)를 읽다.','아무리 가르치고 일러 주어도 알아듣지 못함','1243'],
 ['目不識丁','목불식정','눈 목|아니다 불|알다 식|고무래 정','보고도 고무래 정(丁) 자를 알지 못한다.','글자를 전혀 모름','1432']
].map((row,i)=>({id:i+1,hanja:row[0],reading:row[1],sounds:row[2].split('|').join('\n'),literal:row[3],meaning:row[4],order:row[5].split('').join(' → '),group:i<23?'지혜가 담긴 성어':'속담 한마디'}));
const FIELDS={hanja:'한자',reading:'독음',sounds:'뜻음',literal:'겉뜻',meaning:'속뜻',order:'순서'};
const STORAGE_KEY='hanmun-yare-v1';
const $=(s,root=document)=>root.querySelector(s);
const app=$('#app');
const dialog=$('#dialog');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={front:['hanja'],back:['reading'],stars:[],scope:'all',chunkSize:10,chunk:0};
let settings={...defaults,front:[...defaults.front],back:[...defaults.back],stars:[]};
let storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved){const valid=a=>Array.isArray(a)&&a.length>=1&&a.length<=2&&new Set(a).size===a.length&&a.every(k=>k in FIELDS);if(valid(saved.front)&&valid(saved.back)&&!saved.front.some(k=>saved.back.includes(k))){settings.front=saved.front;settings.back=saved.back;}settings.stars=Array.isArray(saved.stars)?[...new Set(saved.stars.filter(id=>CARDS.some(c=>c.id===id)))]:[];if(['all','stars','chunks'].includes(saved.scope))settings.scope=saved.scope;settings.chunkSize=Math.min(28,Math.max(5,Math.round(Number(saved.chunkSize)||10)));settings.chunk=Math.min(Math.ceil(28/settings.chunkSize)-1,Math.max(0,Math.floor(Number(saved.chunk)||0)));}localStorage.setItem(STORAGE_KEY,JSON.stringify(settings));}catch{storageOK=false;}
let view='home',showBack=false,flipped=new Set(),session=null,completionTimer=null,toastTimer=null,listScroll=0,dialogReturn=null;
let draftFront=[...settings.front],draftBack=[...settings.back];
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(settings));}catch{storageOK=false;}}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,2600);}
function sprout(){return '<div class="sprout" aria-hidden="true"><i class="stem"></i><i class="face"></i></div>';}
function soundMarkup(text){return `<span class="sound-run">${text.split('\n').map(part=>{const match=part.match(/^(.*?)\s+([가-힣])(?:\s+(\([^)]*\)))?$/);if(!match)return esc(part);return `<span class="sound-pair"><span>${esc(match[1])}</span> <b class="sound-circle">${esc(match[2])}</b>${match[3]?` <small class="sound-note">${esc(match[3])}</small>`:''}</span>`;}).join(' ')}</span>`;}
const REFERENCES={6:{meaning:'사전에서는 자기를 알아주는 벗의 죽음을 슬퍼한다는 뜻이에요. 시험 답은 학습지를 따랐어요.'},16:{hanja:'사전의 일반 표기는 漁夫之利예요. 여기서는 학습지의 漁父之利를 사용해요.'}};
function reference(c,keys){return keys.filter(k=>REFERENCES[c.id]?.[k]).map(k=>`<small class="reference-note">참고 · ${REFERENCES[c.id][k]}</small>`).join('');}
function fields(card,keys){return keys.map(k=>`<div class="field ${k}"><span class="field-label">${FIELDS[k]}</span><div class="field-value"${k==='hanja'?' lang="zh-Hant"':''}>${k==='sounds'?soundMarkup(card[k]):esc(card[k])}</div>${view==='session'&&session?.mode==='recall'?'':reference(card,[k])}</div>`).join('');}
function topbar(title,action='home',right=''){return `<header class="topbar"><button class="icon-button" data-action="${action}" aria-label="${action==='exit'?'학습 나가기':'홈으로 돌아가기'}">‹</button><span class="top-title">${title}</span>${right}</header>`;}
function setView(next,restore=false){clearTimeout(completionTimer);clearTimeout(toastTimer);$('#toast').hidden=true;view=next;document.body.dataset.view=next;render();if(restore)requestAnimationFrame(()=>window.scrollTo(0,listScroll));else window.scrollTo(0,0);const heading=$('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
function render(){if(view==='home')renderHome();else if(view==='list')renderList();else if(view==='session')renderSession();else renderRound();}
function renderHome(){app.innerHTML=`<main class="shell screen-enter"><header class="topbar"><div class="brand"><span class="brandmark" aria-hidden="true">文</span>한문 야@르</div><span class="tag">중간시험 준비</span></header><section class="hero"><p class="eyebrow">나의 성어 공부방 · 28장</p><h1>한 장씩,<br>머릿속에 쏙.</h1>${sprout()}<p>무엇을 보고, 무엇을 떠올릴까요?</p></section>${selectionPanel('front','보이는 학습','먼저 보는 면')}${selectionPanel('back','가리는 학습','떠올리는 면')}<div class="home-footer"><p class="selection-summary">${draftFront.map(k=>FIELDS[k]).join(' + ')} <span aria-hidden="true">→</span> ${draftBack.map(k=>FIELDS[k]).join(' + ')}</p><button class="primary animated" data-action="apply">학습하기 <span aria-hidden="true">↗</span></button><p class="footer-note">내 속도로, 한 장씩 익혀요.</p>${!storageOK?'<p class="storage-note">이 환경에서는 별과 설정이 앱을 닫으면 초기화돼요.</p>':''}</div></main>`;}
function selectionPanel(side,title,subtitle){const chosen=side==='front'?draftFront:draftBack,other=side==='front'?draftBack:draftFront;return `<section class="select-panel ${side==='back'?'back-panel':''}" aria-labelledby="${side}-heading"><div class="panel-heading"><span class="round-label" aria-hidden="true">${side==='front'?'앞':'뒤'}</span><h2 id="${side}-heading">${title}</h2><small>최대 2개</small></div><div class="chips" role="group" aria-label="${subtitle}">${Object.entries(FIELDS).map(([key,label])=>`<button class="chip" data-action="field" data-side="${side}" data-key="${key}" aria-pressed="${chosen.includes(key)}" ${other.includes(key)?'disabled':''}>${label}</button>`).join('')}</div></section>`;}
function baseCards(){if(settings.scope==='chunks')return CARDS.slice(settings.chunk*settings.chunkSize,(settings.chunk+1)*settings.chunkSize);return CARDS;}
function listCards(){const base=baseCards();return settings.scope==='stars'?base.filter(c=>settings.stars.includes(c.id)):base;}
function scopeLabel(){return settings.scope==='all'?'전체 카드':settings.scope==='stars'?'중요 카드':`${settings.chunk+1}구간 · ${settings.chunkSize}개씩`;}
function renderList(){const cards=listCards();app.innerHTML=`<main class="shell screen-enter">${topbar('나의 성어 노트','home',`<span class="tag">${cards.length}장</span>`)}<h1 class="page-title">차곡차곡, 내 성어.</h1><p class="page-subtitle">${settings.front.map(k=>FIELDS[k]).join(' + ')} 보고 ${settings.back.map(k=>FIELDS[k]).join(' + ')} 떠올리기</p><div class="mode-grid"><button class="mode-button" data-action="start" data-mode="memory"><span class="mode-symbol" aria-hidden="true">▱</span><strong>암기</strong><small>살짝 열고, 기억하기</small></button><button class="mode-button recall" data-action="start" data-mode="recall"><span class="mode-symbol" aria-hidden="true">✧</span><strong>리콜</strong><small>정답을 골라 확인하기</small></button></div><div class="toolbar"><button class="range-button" data-action="scope" aria-label="학습 범위 설정">${scopeLabel()} <span aria-hidden="true">⌄</span></button><label class="toggle-label">가리는 학습 보기 <button class="switch" role="switch" aria-label="가리는 학습 보기" aria-checked="${showBack}" data-action="show-back"></button></label></div>${settings.scope==='chunks'?`<nav class="chunk-tabs" aria-label="학습 구간">${Array.from({length:Math.ceil(CARDS.length/settings.chunkSize)},(_,i)=>`<button class="chunk-tab" data-action="chunk" data-index="${i}" aria-pressed="${settings.chunk===i}">${i*settings.chunkSize+1}–${Math.min((i+1)*settings.chunkSize,CARDS.length)}</button>`).join('')}</nav>`:''}<div class="list-meta"><span>카드를 누르면 뒤집혀요</span><span>별표 ${settings.stars.length}장</span></div><section class="card-list" aria-label="성어 카드">${cards.length?cards.map(cardMarkup).join(''):'<div class="empty"><strong>아직 별표가 없어요</strong><p>전체 목록에서 기억하고 싶은<br>카드에 별을 눌러 주세요.</p><button class="secondary" data-action="all-cards">전체 카드 보기</button></div>'}</section><p class="footer-note">${cards.length?'여기까지, '+cards.length+'장의 성어.':'별표는 언제든 바꿀 수 있어요.'}</p></main>`;}
function cardMarkup(c){const isFlipped=flipped.has(c.id);return `<article class="study-card${isFlipped?' flipped':''}" data-card="${c.id}"><button class="star" data-action="star" data-id="${c.id}" aria-label="${c.reading} 중요 카드" aria-pressed="${settings.stars.includes(c.id)}">${settings.stars.includes(c.id)?'★':'☆'}</button><button class="flip" data-action="flip" data-id="${c.id}" aria-label="카드 ${c.id} ${isFlipped?'앞면':'뒷면'} 보기"><span class="flip-inner"><span class="face-front" aria-hidden="${isFlipped}">${fields(c,settings.front)}</span><span class="face-back" aria-hidden="${!isFlipped}">${fields(c,settings.back)}</span></span></button>${showBack?`<div class="revealed">${fields(c,settings.back)}</div>`:''}</article>`;}
function openDialog(markup){dialogReturn=document.activeElement;dialog.innerHTML=`<div class="modal-content">${markup}</div>`;if(!dialog.open)dialog.showModal();}
function closeDialog(){dialog.close();if(dialogReturn?.isConnected)dialogReturn.focus({preventScroll:true});}
function dialogHeading(title){return `<div class="modal-heading"><h2>${title}</h2><button class="icon-button" data-action="close-dialog" aria-label="닫기">×</button></div>`;}
function openScope(){openDialog(`${dialogHeading('학습 범위')}<p>오늘 공부할 만큼만 골라요.</p><form id="scope-form"><div class="radio-stack">${[['all','전체 카드 학습'],['stars','중요 카드 ★ 학습'],['chunks','구간 단위로 학습']].map(([value,label])=>`<label class="radio-option"><input type="radio" name="scope" value="${value}" ${settings.scope===value?'checked':''}>${label}</label>`).join('')}</div><div class="range-setting"><label for="chunk-size">한 구간의 카드 <output id="chunk-output">${settings.chunkSize}개</output></label><input id="chunk-size" type="range" min="5" max="28" value="${settings.chunkSize}" aria-label="구간별 카드 개수"><div class="range-ends"><span>5개</span><span>전체 28개</span></div></div><button class="primary animated" type="submit">저장하기</button></form>`);$('#chunk-size').addEventListener('input',e=>{$('#chunk-output').textContent=e.target.value+'개';$('input[value="chunks"]',dialog).checked=true;});$('#scope-form').addEventListener('submit',e=>{e.preventDefault();settings.scope=new FormData(e.target).get('scope');settings.chunkSize=Number($('#chunk-size').value);settings.chunk=Math.min(settings.chunk,Math.ceil(28/settings.chunkSize)-1);save();closeDialog();renderList();});}
function requestStart(mode){listScroll=window.scrollY;const base=baseCards(),starred=base.filter(c=>settings.stars.includes(c.id));if(settings.scope==='stars'){if(!starred.length){openDialog(`${dialogHeading('중요 카드를 골라 주세요')}<p>아직 별표가 없어요. 전체 목록에서 별을 누르면 중요 카드만 학습할 수 있어요.</p><div class="choice-stack"><button class="primary" disabled>중요 카드 학습 · 0장</button><button class="secondary" data-action="all-cards">전체 카드 보기</button></div>`);return;}startSession(mode,starred);return;}if(settings.stars.length){openDialog(`${dialogHeading('어떤 카드를 볼까요?')}<p>${mode==='memory'?'암기':'리콜'} · ${settings.scope==='chunks'?scopeLabel():'나의 성어 노트'}</p><div class="choice-stack"><button class="secondary" data-action="start-choice" data-mode="${mode}" data-scope="all">${settings.scope==='chunks'?'이 구간 전체':'전체 카드'}<small>${base.length}장 차근차근 학습하기</small></button><button class="secondary" data-action="start-choice" data-mode="${mode}" data-scope="stars" ${!starred.length?'disabled':''}>중요 카드 ★<small>${starred.length?starred.length+'장 집중해서 학습하기':'이 구간에는 별표 카드가 없어요'}</small></button></div>`);}else startSession(mode,base);}
function startSession(mode,cards){if(!cards.length){toast('학습할 카드가 없어요.');return;}if(dialog.open)closeDialog();session={results:[],covers:[],mode,queue:[...cards],index:0,passed:0,missed:[],round:1,answered:false,cover:0,options:[],front:[...settings.front],back:[...settings.back]};prepareCard();setView('session');}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
const normalize=s=>s.replace(/[\s.,·/()（）]/g,'');
function signature(c,keys){return keys.map(k=>normalize(c[k])).join('\u0001');}
function makeOptions(card,front,back){const answer=signature(card,back);const validAnswers=new Set(CARDS.filter(c=>signature(c,front)===signature(card,front)).map(c=>signature(c,back)));const seen=new Set(validAnswers);const others=shuffle(CARDS).filter(c=>{const sig=signature(c,back);if(seen.has(sig))return false;seen.add(sig);return true;}).slice(0,3);return shuffle([{card,correct:true,key:answer},...others.map(c=>({card:c,correct:false,key:signature(c,back)}))]);}
function prepareCard(){session.answered=false;session.cover=session.mode==='memory'?(session.covers[session.index]||0):0;session.options=session.mode==='recall'?makeOptions(session.queue[session.index],session.front,session.back):[];}
function renderSession(){const s=session,c=s.queue[s.index],memory=s.mode==='memory',long=s.back.some(k=>['literal','meaning','sounds'].includes(k))||s.back.length>1;app.innerHTML=`<main class="shell session-shell screen-enter">${topbar(s.round===1?'차근차근 학습 중':`${s.round}회차 · 다시 익히기`,'exit',`<span class="tag">${s.index+1}번째 카드</span>`)}<div class="session-heading"><h1>${memory?'기억을 꺼내 볼까요?':'어떤 뜻일까요?'}</h1><span id="feedback" class="feedback" role="status" hidden></span></div><div class="progress-line"><span>${memory?'완료한 카드':'맞춘 카드'}</span><strong class="progress-count" id="progress-count">${s.passed}<span> | ${s.queue.length}</span></strong></div><div class="progress-track" role="progressbar" aria-label="이번 회차 학습 진행" aria-valuenow="${s.index}" aria-valuemin="0" aria-valuemax="${s.queue.length}"><div class="progress-fill" style="width:${s.index/s.queue.length*100}%"></div></div><section class="question-card" aria-label="보이는 학습">${fields(c,s.front)}</section>${memory?`<p class="session-caption">커버를 아래로 끌어 답을 확인해요.</p><section class="answer-well"><div class="answer-content" aria-hidden="true" inert>${fields(c,s.back)}</div><div class="cover" role="slider" tabindex="0" aria-label="정답 커버 · 아래로 내려서 열기" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" aria-valuetext="완전히 가려짐" aria-orientation="vertical"><div class="cover-handle"></div><div class="cover-hint"><strong>먼저 가리고<br>기억해 보세요.</strong><small>생각이 안나면 커버를 조금 내려<br>확인하고 다음 카드로 넘기세요!</small></div></div></section>`:`<p class="session-caption">알맞은 답을 하나 골라 주세요.</p><section class="options ${long?'long-options':''}" aria-label="정답 보기">${s.options.map((o,i)=>`<button class="answer-option" data-action="answer" data-index="${i}" aria-label="${i+1}번 ${s.back.map(k=>o.card[k]).join(', ')}"><div class="option-fields">${fields(o.card,s.back)}</div></button>`).join('')}</section>`}<footer class="session-bottom"><div class="swipe-guide" tabindex="0" aria-label="왼쪽 화살표로 다음 카드, 암기는 오른쪽 화살표로 이전 카드"><strong>← 왼쪽으로 쓱, 다음 카드</strong><p>${memory?'오른쪽으로 밀면 이전 카드로 돌아가요.':'답을 고른 뒤 밀어 주세요.'}</p></div></footer></main>`;if(memory){wireCover();setCover(s.cover);}wireSwipe();}

function setCover(value){session.cover=Math.max(0,Math.min(100,value));const cover=$('.cover'),well=$('.answer-well');if(!cover||!well)return;const open=session.cover>=99.5;if(open)session.cover=100;cover.style.transform=`translateY(${(well.clientHeight-65)*session.cover/100}px)`;cover.classList.toggle('open',open);cover.setAttribute('aria-valuenow',Math.round(session.cover));cover.setAttribute('aria-valuetext',open?'완전히 열림':session.cover===0?'완전히 가려짐':`${Math.round(session.cover)}% 열림`);$('.answer-content').setAttribute('aria-hidden',String(!open));$('.answer-content').inert=!open;$('.cover-hint').innerHTML=open?'아는 게 아니면 다시 덮어요.':'<strong>먼저 가리고<br>기억해 보세요.</strong><small>생각이 안나면 커버를 조금 내려<br>확인하고 다음 카드로 넘기세요!</small>';}
function wireCover(){const cover=$('.cover'),well=$('.answer-well');let drag=null,timer;
const settle=()=>{cover.classList.add('spring');setCover(session.cover===100?100:0);};
cover.addEventListener('pointerdown',e=>{if(e.button!==0)return;clearTimeout(timer);cover.classList.remove('spring');drag={x:e.clientX,y:e.clientY,value:session.cover};cover.setPointerCapture(e.pointerId);cover.focus({preventScroll:true});e.preventDefault();});
cover.addEventListener('pointermove',e=>{if(drag&&Math.abs(e.clientY-drag.y)>=Math.abs(e.clientX-drag.x))setCover(drag.value+(e.clientY-drag.y)/(well.clientHeight-65)*100);});
const release=()=>{if(!drag)return;drag=null;settle();};cover.addEventListener('pointerup',release);cover.addEventListener('pointercancel',release);cover.addEventListener('lostpointercapture',release);
cover.addEventListener('keydown',e=>{const steps={ArrowDown:10,ArrowUp:-10,PageDown:25,PageUp:-25};if(e.key in steps){e.preventDefault();cover.classList.remove('spring');setCover(session.cover+steps[e.key]);}else if(e.key==='Home'||e.key==='End'){e.preventDefault();setCover(e.key==='End'?100:0);}});cover.addEventListener('keyup',e=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End'].includes(e.key))settle();});
cover.addEventListener('wheel',e=>{e.preventDefault();clearTimeout(timer);cover.classList.remove('spring');setCover(session.cover+e.deltaY*.2);timer=setTimeout(()=>{if(cover.isConnected)settle();},180);},{passive:false});}
function wireSwipe(){const surface=$('.session-shell');let start=null;
surface.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;start={x:e.clientX,y:e.clientY};});surface.addEventListener('pointercancel',()=>start=null);
surface.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy)*1.4)return;if(dx<0)nextCard();else previousCard();});
surface.addEventListener('keydown',e=>{if(e.target.closest('button')||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')nextCard();else previousCard();});}
function previousCard(){if(session.mode!=='memory'||session.index===0)return;session.covers[session.index]=session.cover;session.index--;prepareCard();setView('session');}
function answer(index){if(!session||session.answered)return;const choice=session.options[index];if(!choice)return;session.answered=true;if(choice.correct)session.passed++;else session.missed.push(session.queue[session.index]);document.querySelectorAll('.answer-option').forEach((b,i)=>{b.disabled=true;b.classList.add(session.options[i].correct?'correct':i===index?'wrong':'dimmed');if(session.options[i].correct)b.setAttribute('aria-label','정답 · '+b.getAttribute('aria-label'));});const feedback=$('#feedback');feedback.hidden=false;feedback.textContent=choice.correct?'정답!':'다음에 다시 시도!';$('#progress-count').innerHTML=`${session.passed}<span> | ${session.queue.length}</span>`;$('.swipe-guide p').textContent='정답을 확인했다면 왼쪽으로 밀어 주세요.';$('.session-bottom').insertAdjacentHTML('afterbegin',reference(session.queue[session.index],session.back));}
function nextCard(){if(session.mode==='recall'&&!session.answered)return;if(session.mode==='memory'){session.covers[session.index]=session.cover;session.results[session.index]=session.cover===100;session.passed=session.results.filter(Boolean).length;session.missed=session.queue.filter((c,i)=>session.results[i]===false);}session.index++;if(session.index===session.queue.length){setView(session.missed.length?'round':'complete');return;}prepareCard();setView('session');}
function renderRound(){const done=view==='complete';app.innerHTML=`<main class="shell screen-enter">${topbar(done?'학습 완료':'한 번 더 익혀요','exit')}<section class="round-screen">${sprout()}<h1>${done?'완벽해요!':'조금만 더, 내 것으로.'}</h1><p>${done?'모든 카드를 끝까지 익혔어요.<br>차곡차곡 쌓인 기억, 잘했어요.':`아직 남은 <strong>${session.missed.length}장</strong>만 다시 볼게요.<br>서두르지 않아도 괜찮아요.`}</p><span class="round-badge">${session.passed} / ${session.queue.length}장 ${session.mode==='memory'?'완료':'정답'}</span><button class="primary animated" data-action="${done?'return-list':'retry'}">${done?'성어 노트로':'남은 카드 다시 학습하기'} <span aria-hidden="true">→</span></button>${done?'<p class="completion-timer">잠시 후 성어 노트로 돌아가요.</p>':''}</section></main>`;if(done)completionTimer=setTimeout(()=>{session=null;setView('list',true);},3000);}
function exitSession(){if(view==='complete'){session=null;setView('list',true);return;}openDialog(`${dialogHeading('잠깐 쉬어 갈까요?')}<p>별과 학습 설정은 유지돼요.<br>이번 학습은 다음에 처음부터 시작해요.</p><div class="dialog-actions"><button class="secondary" data-action="close-dialog">계속 학습</button><button class="primary" data-action="return-list">목록으로</button></div>`);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;if(action==='field'){const selection=b.dataset.side==='front'?draftFront:draftBack,key=b.dataset.key,i=selection.indexOf(key);if(i>=0){if(selection.length===1){toast('각 면에 하나 이상 골라 주세요.');return;}selection.splice(i,1);}else{if(selection.length===2){toast('각 면에는 두 개까지 고를 수 있어요.');return;}selection.push(key);}renderHome();$(`[data-action="field"][data-side="${b.dataset.side}"][data-key="${key}"]`).focus({preventScroll:true});}
else if(action==='apply'){settings.front=[...draftFront];settings.back=[...draftBack];save();flipped.clear();setView('list');}
else if(action==='home'){draftFront=[...settings.front];draftBack=[...settings.back];setView('home');}
else if(action==='flip'){const id=Number(b.dataset.id),article=b.closest('.study-card');if(flipped.has(id))flipped.delete(id);else flipped.add(id);const on=flipped.has(id);article.classList.toggle('flipped',on);b.setAttribute('aria-label',`카드 ${id} ${on?'앞면':'뒷면'} 보기`);$('.face-front',b).setAttribute('aria-hidden',String(on));$('.face-back',b).setAttribute('aria-hidden',String(!on));}
else if(action==='star'){const id=Number(b.dataset.id),i=settings.stars.indexOf(id);if(i>=0)settings.stars.splice(i,1);else settings.stars.push(id);save();if(settings.scope==='stars'){renderList();}else{b.textContent=i>=0?'☆':'★';b.setAttribute('aria-pressed',String(i<0));$('.list-meta span:last-child').textContent=`별표 ${settings.stars.length}장`;}}
else if(action==='show-back'){showBack=!showBack;const y=window.scrollY;renderList();window.scrollTo(0,y);$('[data-action="show-back"]').focus({preventScroll:true});}
else if(action==='scope')openScope();
else if(action==='close-dialog')closeDialog();
else if(action==='chunk'){settings.chunk=Number(b.dataset.index);save();flipped.clear();renderList();}
else if(action==='all-cards'){settings.scope='all';save();if(dialog.open)closeDialog();setView('list');}
else if(action==='start')requestStart(b.dataset.mode);
else if(action==='start-choice'){const cards=baseCards().filter(c=>b.dataset.scope==='all'||settings.stars.includes(c.id));startSession(b.dataset.mode,cards);}
else if(action==='answer')answer(Number(b.dataset.index));
else if(action==='next')nextCard();
else if(action==='exit')exitSession();
else if(action==='return-list'){if(dialog.open)closeDialog();session=null;setView('list',true);}
else if(action==='retry'){session.queue=[...session.missed];session.results=[];session.covers=[];session.missed=[];session.index=0;session.passed=0;session.round++;prepareCard();setView('session');}
});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
let viewportFrame;
function fitViewport(){cancelAnimationFrame(viewportFrame);viewportFrame=requestAnimationFrame(()=>{const height=Math.floor(window.visualViewport?.height||window.innerHeight);document.documentElement.style.setProperty('--visible-height',height+'px');document.documentElement.classList.toggle('short-viewport',height<700);if(view==='session'&&session.mode==='memory')setCover(session.cover);});}
window.addEventListener('resize',fitViewport);window.visualViewport?.addEventListener('resize',fitViewport);fitViewport();
render();
